Repository SW-FIND-MY-JOB/FindMyJob_FE, pull requests merged in 2025-06, with the labels that each got.

#26 🔧 Kakaomap css 수정
  src/api/authService/authAPI.js
  src/components/kakaoMap/KaKaoMap.module.css
Labels: :hammer: Refactor

#37 ✨ [FEAT/#35] 랜딩페이지 구현
  package-lock.json
  package.json
  src/api/authService/authAPI.js
  src/api/nonAuth/axiosInstance.js
  src/api/notice/noticeAPI.js
  src/components/correction/AiCorrection.jsx
  src/components/correction/AiCorrection.module.css
  src/components/landing/Calendar.jsx
  src/components/landing/Calendar.module.css
  src/components/landing/MainTopArea.jsx
  src/components/landing/MainTopArea.module.css
  src/components/landing/RecruitmentCard.jsx
  src/components/landing/RecruitmentCard.module.css
  src/components/recruitmentNotice/RecruitmentCard.jsx
  src/components/recruitmentNotice/RecruitmentCard.module.css
  src/index.css
  src/pages/main/MainPage.jsx
  src/pages/main/MainPage.module.css
  src/pages/recruitmentNotice/RecruitmentNoticeDetail.jsx
  src/pages/recruitmentNotice/RecruitmentNoticePage.module.css
  src/styles/FullCalendar.css
  src/styles/tippy-custom.css
Labels: ✨ Feature

#39 ✨ [FEAT] 자소서 페이지, 채용정보 페이지 구현
  src/api/coverletterGetList/getList.js
  src/components/Cover-Letter-Question/CoverLetterQuestionForm.jsx
  src/components/cover-letter-row/CoverLetterRow.jsx
  src/components/cover-letter-row/CoverLetterRow.module.css
  src/components/cover-letter/CoverLetterList.jsx
  src/components/cover-letter/CoverLetterList.module.css
  src/components/cover-letter/CoverLetterMain.jsx
  src/components/cover-letter/CoverLetterMain.module.css
  src/components/recruitmentNotice/RecruitmentCard.jsx
  src/components/recruitmentNotice/RecruitmentCard.module.css
  src/pages/coverLetter/CoverLetterPage.jsx
  src/pages/coverlettersearchpage/CoverLetterSearchPage.jsx
  src/pages/coverlettersearchpage/CoverLetterSearchPage.module.css
  src/pages/recruitmentNotice/RecruitmentNoticePage.module.css
Labels: ✨ Feature

#48 🐛 [BUG/#47] 자소서 첨삭 페이지 수정
  src/components/commons/footer/Footer.module.css
  src/components/correction/AiCorrection.module.css
Labels: 🐛 BugFix

#50 💄 [UI/#49] 전체적인 UI 수정
  src/components/commons/footer/Footer.module.css
  src/components/kakaoMap/KakaoMap.module.css
  src/pages/recruitmentNotice/RecruitmentNoticePage.module.css
Labels: :hammer: Refactor

#55 🔨 [MODI/#54] 자소서 작성 페이지 수정
  public/images/ranking_banner.png
  src/components/Cover-Letter-Question/AiScoreModal.jsx
  src/components/Cover-Letter-Question/AiScoreModal.module.css
  src/components/Cover-Letter-Question/CoverLetterQuestion.module.css
  src/components/Cover-Letter-Question/CoverLetterQuestionForm.jsx
  src/components/commons/header/Header.jsx
  src/components/commons/header/Header.module.css
  src/components/landing/MainTopArea.module.css
  src/pages/coverlettersearchpage/CoverLetterSearchPage.module.css
  src/pages/main/MainPage.jsx
  src/pages/main/MainPage.module.css
  src/pages/recruitmentNotice/RecruitmentNoticeDetail.jsx
Labels: ✨ Feature, :hammer: Refactor

#56 ✨[FEAT/#52] 랭킹페이지 구현
  package-lock.json
  package.json
  src/api/rankingApi/Ranking.js
  src/components/commons/header/Header.jsx
  src/components/commons/header/Header.module.css
  src/components/cover-letter-row/CoverLetterRow.jsx
  src/components/cover-letter-row/CoverLetterRow.module.css
  src/components/cover-letter/CoverLetterList.jsx
  src/components/cover-letter/CoverLetterList.module.css
  src/components/cover-letter/CoverLetterMain.jsx
  src/components/cover-letter/CoverLetterMain.module.css
  src/components/mypage/MyResume.jsx
  src/components/mypage/MyResume.module.css
  src/components/mypage/ScrapResume.jsx
  src/components/mypage/ScrapResume.module.css
  src/components/rankingComponent/RankingList.jsx
  src/components/rankingComponent/RankingList.module.css
  src/pages/coverLetter/CoverLetterPage.jsx
  src/pages/coverLetter/CoverLetterPage.module.css
  src/pages/myPage/MyPage.module.css
  src/pages/ranking/Ranking.jsx
  src/pages/ranking/Ranking.module.css
Labels: ✨ Feature, :hammer: Refactor

#58 ✨ [FEAT/#57] 자소서 정규분포 차트 시각화
  package-lock.json
  package.json
  src/components/Cover-Letter-Question/AiScoreModal.jsx
  src/components/Cover-Letter-Question/AiScoreModal.module.css
  src/components/Cover-Letter-Question/CoverLetterQuestionForm.jsx
  src/components/Cover-Letter-Question/HistogramToNormalChart.jsx
  src/components/correction/AiCorrection.module.css
  src/components/correction/MyContent.module.css
  src/layouts/MainLayout.module.css
Labels: ✨ Feature, :hammer: Refactor

#60 💄 [FEAT/#59] 전체적인 UI수정
  src/components/Cover-Letter-Question/CoverLetterQuestion.module.css
  src/components/rankingComponent/RankingList.jsx
  src/pages/ranking/Ranking.module.css
  src/pages/recruitmentNotice/RecruitmentNoticeDetail.jsx
Labels: :hammer: Refactor

#62 💄 [UI/#61] 랭킹페이지 UI 수정
  src/components/rankingComponent/RankingList.module.css
Labels: :hammer: Refactor

#64 ✨ [FEAT/#63] 포인트 내역 페이지 구현
  src/api/myPage/myPageAPI.js
  src/components/mypage/ChangePassword.module.css
  src/components/mypage/DeleteAccount.module.css
  src/components/mypage/MyResume.module.css
  src/components/mypage/PointHistory.jsx
  src/components/mypage/PointHistory.module.css
  src/components/mypage/ScrapResume.module.css
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPage.module.css
Labels: ✨ Feature

#65 🔀 develop브랜치 병합
  package-lock.json
  package.json
  public/images/ranking_banner.png
  src/api/myPage/myPageAPI.js
  src/api/rankingApi/Ranking.js
  src/components/Cover-Letter-Question/AiScoreModal.jsx
  src/components/Cover-Letter-Question/AiScoreModal.module.css
  src/components/Cover-Letter-Question/CoverLetterQuestion.module.css
  src/components/Cover-Letter-Question/CoverLetterQuestionForm.jsx
  src/components/Cover-Letter-Question/HistogramToNormalChart.jsx
  src/components/commons/header/Header.jsx
  src/components/commons/header/Header.module.css
  src/components/correction/AiCorrection.module.css
  src/components/correction/MyContent.module.css
  src/components/cover-letter-row/CoverLetterRow.jsx
  src/components/cover-letter-row/CoverLetterRow.module.css
  src/components/cover-letter/CoverLetterList.jsx
  src/components/cover-letter/CoverLetterList.module.css
  src/components/cover-letter/CoverLetterMain.jsx
  src/components/cover-letter/CoverLetterMain.module.css
  src/components/landing/MainTopArea.module.css
  src/components/mypage/ChangePassword.module.css
  src/components/mypage/DeleteAccount.module.css
  src/components/mypage/MyResume.jsx
  src/components/mypage/MyResume.module.css
  src/components/mypage/PointHistory.jsx
  src/components/mypage/PointHistory.module.css
  src/components/mypage/ScrapResume.jsx
  src/components/mypage/ScrapResume.module.css
  src/components/rankingComponent/RankingList.jsx
  src/components/rankingComponent/RankingList.module.css
  src/layouts/MainLayout.jsx
  src/layouts/MainLayout.module.css
  src/pages/coverLetter/CoverLetterPage.jsx
  src/pages/coverLetter/CoverLetterPage.module.css
  src/pages/coverlettersearchpage/CoverLetterSearchPage.module.css
  src/pages/main/MainPage.jsx
  src/pages/main/MainPage.module.css
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPage.module.css
  src/pages/ranking/Ranking.jsx
  src/pages/ranking/Ranking.module.css
  src/pages/recruitmentNotice/RecruitmentNoticeDetail.jsx
  src/router/Routers.jsx
Labels: 🌏 Deploy, ✨ Feature

#66 🔀 develop브랜치 병합
  src/components/commons/header/Header.module.css
Labels: :hammer: Refactor

#68 🐛 [BUG/#67] 글작성 페이지 에러 수정
  src/components/Cover-Letter-Question/CoverLetterQuestionForm.jsx
  src/components/Cover-Letter-Question/HistogramToNormalChart.jsx
Labels: 🐛 BugFix

#72 🔀 develop브랜치 병합
  src/components/mypage/MyResume.jsx
  src/components/mypage/MyResume.module.css
  src/components/mypage/PointHistory.jsx
  src/components/mypage/PointHistory.module.css
  src/components/mypage/ScrapResume.jsx
  src/components/mypage/ScrapResume.module.css
  src/components/recruitmentNotice/RecruitmentCard.jsx
  src/pages/coverlettersearchpage/CoverLetterSearchPage.jsx
Labels: 🐛 BugFix

#74 🐛 [BUG/#73] UI 수정
  src/components/cover-letter-row/CoverLetterRow.jsx
  src/components/mypage/MyResume.module.css
Labels: 🐛 BugFix

#75 🔀 develop브랜치 병합
  src/components/cover-letter-row/CoverLetterRow.jsx
  src/components/mypage/MyResume.module.css
Labels: 🐛 BugFix

#76 🔀 develop브랜치 병합
  src/components/kakaoMap/KakaoMap.jsx
Labels: 🐛 BugFix

#78 ⚡ [PI/#77] 일자리 정보 카페 페이지 수정
  public/images/강남 취창업허브센터.jpg
  public/images/구로청년공간 청년이룸.jpg
  public/images/노량진청년일자리센터.jpg
  public/images/노원구 청년일자리센터 청년내일.jpg
  public/images/도봉구 청년취업지원센터.png
  public/images/마포청년창업취업지원센터 나루.jpg
  public/images/성동 청년일다방.png
  public/images/양천 청년일자리카페.jpg
  public/images/용산청년지음.jpg
  src/components/kakaoMap/KakaoMap.jsx
  src/data/jobCafes.json
Labels: :hammer: Refactor
